### ISSUE TITLE
Fan is not separate functionality since 5.2.0

### ISSUE THREAD

**Issue by 1094767056** [codyc1515/homebridge-panasonic-air-conditioner#56] opened 2021-02-15 15:06 UTC
Hello, 
By default my AC has only Cool, Dry, Heat and Auto modes, no Fan only mode. However up until v5.2.0 it was possible to use the AC as fan only, without heating, cooling, etc. Currently in version 5.2.0 the Fan accessory only controls the fan speed, rather than giving the ability to run as Fan only. Could this be solved somehow? Thank you! :)

**Comment by codyc1515** [comment] 2021-04-17 20:20
Duplicate of #48

**Closed as completed by codyc1515** 2021-04-17 20:20 UTC
Labels: enhancement
